logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.163.130 #主机名
    port: 5672  #端口
    virtualHost: / #虚拟主机
    username: itcast #用户名
    password: 123321 #密码
    listener:
      simple:
        prefetch: 1 #每次只获取一条消息，处理完成才获取下一条